import Head from "next/head";
import { useEffect } from "react";

export default function Home(initialData) {
  useEffect(() => {
    console.log(initialData);
  });

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />

        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>GIPHY Search App</h1>
      <div class="giphy-search-results-grid">
        {initialData.catGiphys.data.map((each, index) => {
          return (
            <div key="index">
              <h3>{each.title}</h3>
              <img src={each.images.original.url} alt={each.title} />
            </div>
          );
        })}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  let catGiphys = await fetch(
    "https://api.giphy.com/v1/gifs/search?q=cats&api_key=BfmrWj2ktbt5f5iULLPNyr5gO4IbFBCs&limit=10"
  );
  catGiphys = await catGiphys.json();
  return { props: { catGiphys: catGiphys } };
}
